version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      tanstack:
        patterns:
          - '@tanstack/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      intlayer:
        patterns:
          - 'intlayer'
          - 'react-intlayer'
          - 'vite-intlayer'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-plugin-*'
          - '@typescript-eslint/*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'vite-plugin-*'
      testing:
        patterns:
          - '@testing-library/*'
          - 'jsdom'
          - 'vitest'
      types:
        patterns:
          - '@types/*'
        exclude-patterns:
          - '@types/react'
          - '@types/react-dom'
      misc:
        patterns:
          - '*'
        exclude-patterns:
          - '@tanstack/*'
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'daisyui'
          - 'eslint-plugin-better-tailwindcss'
          - 'intlayer'
          - 'react-intlayer'
          - 'vite-intlayer'
          - 'eslint'
          - 'eslint-plugin-*'
          - '@typescript-eslint/*'
          - 'vite'
          - '@vitejs/*'
          - 'vite-plugin-*'
          - '@testing-library/*'
          - 'jsdom'
          - 'vitest'
          - '@types/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
