services:
  app:
    image: ${APP_IMAGE}
    networks:
      - dokploy-network
    ports:
      - 3000
    environment:
      NITRO_DIRECTUS_URL: ${DIRECTUS_URL}
      NITRO_APP_URL: ${APP_URL}
    labels:
      - 'traefik.http.middlewares.app-compress.compress=true'
      - 'traefik.http.services.app-svc.loadbalancer.server.port=3000'
      - 'traefik.http.routers.app.rule=Host(`${APP_HOST}`)'
      - 'traefik.http.routers.app.entrypoints=websecure'
      - 'traefik.http.routers.app.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.app.middlewares=app-compress'
      - 'traefik.http.routers.app.service=app-svc'
    healthcheck:
      test:
        ['CMD-SHELL', 'wget -qO- http://localhost:3000/api/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

networks:
  dokploy-network:
    external: true
